### ISSUE TITLE
No src directory when pulling exercise

### ISSUE THREAD

**Issue by bmulvihill** [exercism/xcrystal#63]
When pulling a new exercise from exercism it isn't immediately apparent that one needs to create a src directory to hold their code file, should this be handled for the user? Or should we update the docs to explicitly mention a src directory should be created with any applicable code files? Or am I missing something and this is already handled 😄 ?

**Comment by mhelmetag** [comment]
Ah... this was based off of what the xclojure track was doing. It looks like that track has a file with a blank module.

I think this can either be solved by adding a blank file to each exercise's src dir (blank so that module or class isn't hardcoded in their and the user can pick based on their solution without bias). Or, as you said, we can just add a bit in the docs saying you'll need to make a new file in the src dir.

Thoughts? Or other solutions?

**Comment by bmulvihill** [comment]
Yeah I think a blank file would work, at least it would make it (more) obvious as to where they should be writing their solution.  The file could have a small comment in it with simple instructions stating "Please implement your solution to EXERCISE_NAME in this file" maybe?

**Comment by mhelmetag** [comment]
Sounds good! I think we can go with that solution then. I can pick this up.
